version: "3.8"
services:
    web:
        container_name: web
        image: nginx:alpine
        volumes:
            - ./src:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - php-fpm
        networks:
            - pos_app_network

    php-fpm:
        container_name: posapp
        build:
            context: .
            dockerfile: Dockerfile
            target: php
            args:
                - APP_ENV=${APP_ENV}
        volumes:
            - ./src:/var/www
        environment:
            - APP_ENV=${APP_ENV}
        networks:
            - pos_app_network
        working_dir: /var/www
        depends_on:
            - mariadb
            - redis

    mariadb:
        container_name: pos_db
        image: mariadb:latest
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_DATABASE: ${DB_DATABASE:-pos}
            MYSQL_USER: ${DB_USERNAME:-app}
            MYSQL_PASSWORD: ${DB_PASSWORD:-root}
        env_file:
            - ./src/.env
        volumes:
            - pos-db-data:/var/lib/mysql
            - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro
        networks:
            - pos_app_network
    redis:
        container_name: pos_redis
        image: redis:alpine
        ports:
            - "${REDIS_PORT:-6379}:6379"
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
        command: redis-server --appendonly yes ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}
        networks:
            - pos_app_network

networks:
    pos_app_network:
        driver: bridge

volumes:
    pos-db-data:
